language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

install:
  - bash -x devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export PATH=$HOME/miniconda3/bin:$PATH

script:

  # Create an environment for testing
  - conda create --yes -n test python=$python
  - source activate test
  - conda config --add channels $ORGNAME
  
  - conda build devtools/conda-recipe
  - conda install --yes --use-local ${PACKAGENAME}-dev
  # Install testing dependencies
  - conda install --yes --quiet pytest pytest-cov
  # Test the package
  - cd devtools && py.test ${PACKAGENAME} --cov=${PACKAGENAME} && cd ..
  
env:
  matrix:
    - python=2.7 CONDA_PY=27
    - python=3.4 CONDA_PY=34
    - python=3.5 CONDA_PY=35
     
  global:
    - ORGNAME="omnia"
    - PACKAGENAME="protons"
        
after_success:
  - echo "after_success"
  - cd devtools && coveralls && cd .. 

  # - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then source devtools/travis-ci/after_success.sh; fi
